allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ssd-fast
parameters:
  diskSelector: ssd,fast
  fsType: xfs
  nodeSelector: lindon.endor/storage-ssd=fast
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
