---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
  labels:
    name: pihole
  name: pihole
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-config
  namespace: pihole
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/nfs_fast/pihole
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: pihole
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: pihole-config

