---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
  labels:
    name: nextcloud
  name: nextcloud
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-app
  namespace: nextcloud
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/nfs_fast/nextcloud-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app
  namespace: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: nextcloud-app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  capacity:
    storage: 768Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/nfs4/nextcloud-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 768Gi
  volumeName: nextcloud-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-tmp
  namespace: nextcloud
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # A temporary PV can and should be local to the pod
  hostPath:
    path: /mnt/ssd/nextcloud-tmp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-tmp
  namespace: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: fpm
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nextcloud
data:
  default.conf: |
    log_format upstreaminfo
      '$remote_addr - $request_id - [$proxy_add_x_forwarded_for] - '
      '$remote_user [$time_local] "$request" $status $body_bytes_sent '
      '"$http_referer" "$http_user_agent" $request_length $request_time '
      '$upstream_addr $upstream_response_length '
      '$upstream_response_time $upstream_status';
    log_format alt
      '$http_x_real_ip - $request_id - [$proxy_add_x_forwarded_for] - '
      '$remote_user [$time_local] "$request" $status $body_bytes_sent '
      '"$http_referer" "$http_user_agent" - $request_length $request_time';

    upstream php-handler {
        server 127.0.0.1:9000;
    }

    server {
        listen 80;
        server_name localhost;

        client_max_body_size 5120M;
        fastcgi_buffers 64 4K;

        access_log  /dev/stdout alt;
        error_log   /dev/stderr;

        gzip on;
        gzip_vary on;
        gzip_comp_level 4;
        gzip_min_length 256;
        gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
        gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

        add_header Referrer-Policy                    "no-referrer"   always;
        add_header X-Content-Type-Options             "nosniff"       always;
        add_header X-Download-Options                 "noopen"        always;
        add_header X-Frame-Options                    "SAMEORIGIN"    always;
        add_header X-Permitted-Cross-Domain-Policies  "none"          always;
        add_header X-Robots-Tag                       "none"          always;
        add_header X-XSS-Protection                   "1; mode=block" always;
        add_header Strict-Transport-Security          "max-age=15552000; includeSubDomains" always;
        fastcgi_hide_header X-Powered-By;

        root /var/www/html;
        index index.php index.html /index.php$request_uri;

        location = / {
            if ( $http_user_agent ~ ^DavClnt ) {
                return 302 /remote.php/webdav/$is_args$args;
            }
        }

        location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
        }

        location ^~ /.well-known {
            location = /.well-known/carddav { return 301 /remote.php/dav/; }
            location = /.well-known/caldav  { return 301 /remote.php/dav/; }

            location /.well-known/acme-challenge    { try_files $uri $uri/ =404; }
            location /.well-known/pki-validation    { try_files $uri $uri/ =404; }

            return 301 /index.php$request_uri;
        }

        location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)(?:$|/)  { return 404; }
        location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console)                { return 404; }

        location ~ \.php(?:$|/) {
            rewrite ^/(?!info|index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy) /index.php$request_uri;
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;
            set $path_info $fastcgi_path_info;

            try_files $fastcgi_script_name =404;

            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $path_info;
            fastcgi_param HTTPS on;

            fastcgi_param modHeadersAvailable true;
            fastcgi_param front_controller_active true;
            fastcgi_pass php-handler;

            fastcgi_intercept_errors on;
            fastcgi_request_buffering off;

            proxy_temp_path /var/tmp/nginx;
        }

        location ~ \.(?:css|js|svg|gif|png|jpg|ico)$ {
            try_files $uri /index.php$request_uri;
            expires 6M;
            access_log off;
        }

        location ~ \.woff2?$ {
            try_files $uri /index.php$request_uri;
            expires 7d;
            access_log off;
        }

        location /remote {
            return 301 /remote.php$request_uri;
        }

        location / {
            try_files $uri $uri/ /index.php$request_uri;
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fpm-php-www-config
  namespace: nextcloud
data:
  www.conf: |
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    pm = dynamic
    pm.max_children = 6
    pm.start_servers = 2
    pm.min_spare_servers = 2
    pm.max_spare_servers = 4
    pm.max_requests = 300

    php_admin_value[upload_max_filesize] = 5120M
    php_admin_value[error_log] = /var/log/fpm-php.www.log
    php_admin_value[post_max_size] = 5120M
    php_admin_value[memory_limit] = 512M
    php_admin_value[upload_tmp_dir] = /var/www/html/data/tmp

    php_admin_flag[log_errors] = on
    php_flag[display_errors] = on
  docker.conf: |
    [global]
    error_log = /dev/stderr
    ;error_log = /var/log/php-fpm.log
    log_limit = 8192
    [www]
    access.log = /dev/stdout
    clear_env = no
    catch_workers_output = yes
    decorate_workers_output = no
  zz-docker.conf: |
    [global]
    daemonize = no
    ;error_log = /var/log/php-fpm.zz.log
    [www]
    listen = 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      tier: app
  template:
    metadata:
      labels:
        app: nextcloud
        tier: app
    spec:
      # nodeSelector for nextcloud upgrades
      #nodeSelector:
      #  kubernetes.io/hostname: forlond-3
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chmod 0770 /var/tmp/nginx && chown 82:0 /var/tmp/nginx && ls -ld /var/tmp/nginx /var/www/html /var/www/html/data && ls -l /var/www/html"]
          volumeMounts:
            - name: nextcloud-app
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/html/data
            - name: nextcloud-tmp
              mountPath: /var/tmp/nginx
      containers:
        - name: nginx
          image: nginx:1.23.2-alpine
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 16Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nextcloud-app
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/html/data
            - name: nextcloud-tmp
              mountPath: /var/tmp/nginx
          ports:
            - containerPort: 80
        - name: nextcloud
          image: nextcloud:25.0.3-fpm-alpine
          ports:
            - containerPort: 9000
          #livenessProbe:
          #  path: /ocs/v2.php/apps/serverinfo/api/v1/info
          #  port: 80
          #  httpHeaders:
          #    - name: NC-Token
          #      value: YSsFQ4Ro3W3j60oP5v6JsulLZRUO2O1PQqh0xSXKVMgqlO8eTZtBUScJhbSLrs9l
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: fpm-php-www-config
              mountPath: /usr/local/etc/php-fpm.d
            - name: nextcloud-app
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/html/data
          env:
            - name: REDIS_HOST
              value: redis
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: PHP_UPLOAD_LIMIT
              value: 5120M
            - name: PHP_POST_LIMIT
              value: 5120M
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: username
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: cloud.neumanny.live nextcloud.pictaviensis.regnum
            - name: TRUSTED_PROXIES
              value: cloud.neumanny.live 172.104.150.140 10.42.0.0/15
            - name: OVERWRITEHOST
              value: cloud.neumanny.live
            - name: OVERWRITEPROTOCOL
              value: https
      volumes:
        - name: fpm-php-www-config
          configMap:
            name: fpm-php-www-config
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nextcloud-app
          persistentVolumeClaim:
            claimName: nextcloud-app
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - name: nextcloud-tmp
          persistentVolumeClaim:
            claimName: nextcloud-tmp
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: pictaviensis.regnum/storage
                      operator: In
                      values:
                        - "true"
                topologyKey: kubernetes.io/hostname
              weight: 60
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - nextcloud
                topologyKey: kubernetes.io/hostname
              weight: 20
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            pictaviensis.regnum/type: rpi4-large
          containers:
            - name: nextcloud
              image: nextcloud:25.0.3-fpm-alpine
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date ; apk add sudo perl nodejs ; echo "Executing Nextcloud's cron job" ; date ; sudo -u '#82' php -d memory_limit=-1 --define apc.enable_cli=1 -f /var/www/html/cron.php ; sudo -u '#82' php -d memory_limit=-1 -f /var/www/html/occ mail:account:sync 1 ; sudo -u '#82' php -d memory_limit=-1 -f /var/www/html/occ mail:clean-up ; date
              resources:
                limits:
                  cpu: 2500m
                  memory: 2048Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
              volumeMounts:
                - name: fpm-php-www-config
                  mountPath: /usr/local/etc/php-fpm.d
                - name: nextcloud-app
                  mountPath: /var/www/html
                - name: nextcloud-data
                  mountPath: /var/www/html/data
              env:
                - name: REDIS_HOST
                  value: redis
                - name: POSTGRES_HOST
                  value: postgresql
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: db
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: username
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: password
                - name: PHP_UPLOAD_LIMIT
                  value: 5120M
                - name: PHP_POST_LIMIT
                  value: 5120M
                - name: NEXTCLOUD_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-admin
                      key: username
                - name: NEXTCLOUD_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: nextcloud-admin
                      key: password
                - name: NEXTCLOUD_TRUSTED_DOMAINS
                  value: cloud.neumanny.live nextcloud.pictaviensis.regnum
                - name: TRUSTED_PROXIES
                  value: cloud.neumanny.live 172.104.150.140 10.42.0.0/15
                - name: OVERWRITEHOST
                  value: cloud.neumanny.live
                - name: OVERWRITEPROTOCOL
                  value: https
          volumes:
            - name: fpm-php-www-config
              configMap:
                name: fpm-php-www-config
            - name: nextcloud-app
              persistentVolumeClaim:
                claimName: nextcloud-app
            - name: nextcloud-data
              persistentVolumeClaim:
                claimName: nextcloud-data
          restartPolicy: OnFailure

