---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
  labels:
    name: nextcloud
  name: nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app
  namespace: nextcloud
spec:
  storageClassName: longhorn-ssd-slow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  storageClassName: longhorn-hdd-crypto
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fpm-php-www-config
  namespace: nextcloud
data:
  www.conf: |
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    pm = dynamic
    pm.max_children = 10
    pm.start_servers = 2
    pm.min_spare_servers = 1
    pm.max_spare_servers = 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextcloud
      tier: app
  template:
    metadata:
      labels:
        app: nextcloud
        tier: app
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:22.2.0-fpm-alpine
          resources:
            limits:
              memory: 768Mi
              cpu: "1"
            requests:
              memory: 64Mi
              cpu: 100m
          volumeMounts:
            # - name: fpm-php-www-config
            #   mountPath: /usr/local/etc/php-fpm.d
            - name: nextcloud-app
              mountPath: /var/www/html
            - name: nextcloud-data
              mountPath: /var/www/html/data
          env:
            - name: REDIS_HOST
              value: redis
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: username
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: cloud.neumanny.live
            - name: TRUSTED_PROXIES
              value: cloud.neumanny.live 172.104.150.140 10.42.0.0/15
          ports:
            - containerPort: 9000
      volumes:
        - name: fpm-php-www-config
          configMap:
            name: fpm-php-www-config
        - name: nextcloud-app
          persistentVolumeClaim:
            claimName: nextcloud-app
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
              - matchExpressions:
                  - key: lindon.endor/machine-type
                    operator: In
                    values:
                      - pi4-large
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nextcloud
              topologyKey: kubernetes.io/hostname
---
