---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
  labels:
    name: nextcloud
  name: nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app
  namespace: nextcloud
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: nextcloud
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      tier: app
  template:
    metadata:
      labels:
        app: nextcloud
        tier: app
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.3-alpine
          resources:
            limits:
              memory: 64Mi
              cpu: 200m
            requests:
              memory: 32Mi
              cpu: 100m
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-app
            - mountPath: /var/www/html/data
              name: nextcloud-data
          env:
            - name: NGINX_HOST
              value: cloud.neumanny.live
            # - name: NGINX_PORT
            #   value: "80"
          ports:
            - containerPort: 80
        - name: nextcloud
          image: nextcloud:22.2.0-fpm-alpine
          resources:
            limits:
              cpu: "1"
              memory: 768Mi
            requests:
              memory: 128Mi
              cpu: 200m
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-app
            - mountPath: /var/www/html/data
              name: nextcloud-data
          env:
            - name: REDIS_HOST
              value: redis
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: username
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.lorion cloud.neumanny.live
          ports:
            - containerPort: 9000
      volumes:
        - name: nextcloud-app
          persistentVolumeClaim:
            claimName: app
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nextcloud
              topologyKey: kubernetes.io/hostname
---
