---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    name: nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app
  namespace: nextcloud
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "4Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: nextcloud
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "600Gi"
---
kind: Service
apiVersion: v1
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextcloud
      tier: app
  template:
    metadata:
      labels:
        app: nextcloud
        tier: app
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:22.2.0-fpm-alpine
          resources:
            limits:
              memory: "768Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: 200m
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-app
            - mountPath: /var/www/html/data
              name: nextcloud-data
          env:
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: username
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin
                  key: password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.arnor nextcloud.aman cloud.neumanny.live
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-password
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-password
                  key: password
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_HOST
              value: mariadb
            - name: REDIS_HOST
              value: redis
          ports:
            - containerPort: 9000
      volumes:
        - name: nextcloud-app
          persistentVolumeClaim:
            claimName: app
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: data
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                - key: tier
#                  operator: NotIn
#                  values:
#                    - db
#                    - cache
---

