---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    name: nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: nextcloud
spec:
  storageClassName: longhorn-ssd-fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "640Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: postgresql
  namespace: nextcloud
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: nextcloud
  labels:
    app: postgresql
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      tier: db
  template:
    metadata:
      labels:
        app: postgresql
        tier: db
    spec:
      containers:
        - name: postgresql
          image: postgres:14.1-alpine
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
            requests:
              memory: 256Mi
              cpu: 200m
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/14.1
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: db
          ports:
            - containerPort: 5432
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgresql
      nodeSelector:
        pictaviensis.regnum/storage: "true"
        pictaviensis.regnum/storage-ssd: "fast"

