---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    name: nextcloud
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-postgresql
  namespace: nextcloud
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/nfs_fast/nextcloud-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "4Gi"
  volumeName: nextcloud-postgresql
---
kind: Service
apiVersion: v1
metadata:
  name: postgresql
  namespace: nextcloud
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: nextcloud
  labels:
    app: postgresql
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      tier: db
  template:
    metadata:
      labels:
        app: postgresql
        tier: db
    spec:
      # nodeSelector for nextcloud upgrades
      nodeSelector:
        kubernetes.io/hostname: forlond-3
      containers:
        - name: postgresql
          image: postgres:15.1-alpine
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/15
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: db
          ports:
            - containerPort: 5432
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgresql
      #nodeSelector:
      #  pictaviensis.regnum/storage: "true"
      #  pictaviensis.regnum/storage-ssd: "fast"

