---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    name: nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: nextcloud
spec:
  storageClassName: longhorn-ssd-fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nextcloud
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: nextcloud
  labels:
    app: redis
    tier: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: cache
  template:
    metadata:
      labels:
        app: redis
        tier: cache
    spec:
      containers:
        - name: redis
          image: redis:6.2.6-alpine
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 32Mi
              cpu: 100m
          volumeMounts:
            - mountPath: /data
              name: redis
          ports:
            - containerPort: 6379
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
      nodeSelector:
        pictaviensis.regnum/storage-ssd: "fast"

