{{ if .Values.regex }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-regex
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  regex.list: |
  {{- range .Values.regex }}
    {{ . }}
  {{- end }}
{{ end }}
