---
apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
  labels:
    name: wireguard


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-wireguard
  namespace: wireguard
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "UTC"
  SERVERPORT: "31820"
  PEERS: "2"
  PEERDNS: "10.43.0.10"
  ALLOWEDIPS: "0.0.0.0/0, ::/0"
  INTERNAL_SUBNET: "10.13.13.0"

